// Generated by CoffeeScript 1.6.1
var Guide;

Guide = (function() {

  Guide.prototype.options = {
    grid: {
      align: "center",
      x: {
        major: 240,
        minor: 60,
        gutter: 10
      },
      y: {
        major: 80,
        minor: 20,
        gutter: 0
      }
    }
  };

  function Guide(options) {
    if (options == null) {
      options = {};
    }
    $.extend(this.options, options);
    this.show();
  }

  Guide.prototype.show = function() {
    if (!this.canvas) {
      this._createCanvas();
    }
    return this.canvas.style.visbility = "visible";
  };

  Guide.prototype.hide = function() {
    return this.canvas.style.visbility = "hidden";
  };

  Guide.prototype.update = function() {
    console.log("updating");
    this.canvas.width = Math.max(document.body.clientWidth, window.innerWidth);
    this.canvas.height = Math.max(document.body.clientHeight, window.innerHeight);
    return this._drawGridlines();
  };

  Guide.prototype._drawGridlines = function() {
    var context;
    context = this.canvas.getContext('2d');
    context.strokeStyle = "rgba(52, 141, 190, 0.2)";
    if (this.options.grid.x.gutter > 0) {
      context.lineWidth = this.options.grid.x.gutter;
      this._drawGrid(context, this.options.grid.x.major, 0);
    }
    if (this.options.grid.y.gutter > 0) {
      context.lineWidth = this.options.grid.y.gutter;
      this._drawGrid(context, 0, this.options.grid.y.major);
    }
    context.strokeStyle = "rgba(0,0,0,0.2)";
    context.lineWidth = 1;
    this._drawGrid(context, this.options.grid.x.minor, this.options.grid.y.minor);
    context.strokeStyle = "rgba(0, 131, 255, 0.5)";
    context.lineWidth = 1;
    return this._drawGrid(context, this.options.grid.x.major, this.options.grid.y.major);
  };

  Guide.prototype._drawGrid = function(context, xUnit, yUnit) {
    var left, top, _results;
    left = 0;
    top = 0;
    if (this.options.grid.align === 'center') {
      left = this.canvas.width / 2 % xUnit;
    }
    if (yUnit > 0) {
      while (top < this.canvas.height) {
        context.beginPath();
        context.moveTo(0, top);
        context.lineTo(this.canvas.width, top);
        context.stroke();
        top += yUnit;
      }
    }
    if (xUnit > 0) {
      _results = [];
      while (left < this.canvas.width) {
        context.beginPath();
        context.moveTo(left, 0);
        context.lineTo(left, this.canvas.height);
        context.stroke();
        _results.push(left += xUnit);
      }
      return _results;
    }
  };

  Guide.prototype._createCanvas = function() {
    var _this = this;
    this.canvas = document.createElement("canvas");
    this.canvas.className = "guides";
    this.canvas.style.position = "absolute";
    this.canvas.style.margin = 0;
    this.canvas.style.top = 0;
    this.canvas.style.left = 0;
    this.canvas.style['z-index'] = 9999;
    this.update();
    document.body.appendChild(this.canvas);
    return $(window).resize(function() {
      return _this.update();
    });
  };

  return Guide;

})();
